name: Bump version on dev/master brach
env:
  COMMIT_AUTHOR_NAME: Admin
  COMMIT_AUTHOR_EMAIL: admin@meltstudio.co
on: 
  pull_request_target:
    types:
      - closed
    branches:
      - 'dev'
      - 'master'

jobs:
  bump_minor:
    name: Automatic bump minor
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature/')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-packager: yarn
      - run: yarn install
      - run: |
          yarn bumpMinor | grep -oE '[^ ]+$' > bumpResults.txt
          
          androidBuild=$(sed -n 5p bumpResults.txt)
          iosBuild=$(sed -n 4p bumpResults.txt)
          packageVersion=$(sed -n 1p bumpResults.txt)

          echo "COMMIT_MESSAGE='[update] new version to ${packageVersion} and build number to ${iosBuild} (iOS) and ${androidBuild} (Android)'" >> $GITHUB_ENV

          rm bumpResults.txt
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{env.COMMIT_AUTHOR_NAME}}
          author_email: ${{env.COMMIT_AUTHOR_EMAIL}}
          message: ${{env.COMMIT_MESSAGE}}
          add: '.'
  bump_patch:
    name: Automatic bump patch
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'bug/')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-packager: yarn
      - run: yarn install
      - run: |
          yarn bumpPatch | grep -oE '[^ ]+$' > bumpResults.txt
          
          androidBuild=$(sed -n 5p bumpResults.txt)
          iosBuild=$(sed -n 4p bumpResults.txt)
          packageVersion=$(sed -n 1p bumpResults.txt)

          echo "COMMIT_MESSAGE='[fix] new version to ${packageVersion} and build number to ${iosBuild} (iOS) and ${androidBuild} (Android)'" >> $GITHUB_ENV
          
          rm bumpResults.txt

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{env.COMMIT_AUTHOR_NAME}}
          author_email: ${{env.COMMIT_AUTHOR_EMAIL}}
          message: ${{env.COMMIT_MESSAGE}}
          add: '.'
      